name: camera_windows
description: A Flutter plugin for getting information about and controlling the camera on Windows.
repository: https://github.com/flutter/packages/tree/main/packages/camera/camera_windows
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
version: 0.2.6+2
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: camera
    platforms:
      windows:
        pluginClass: CameraWindows
        dartPluginClass: CameraWindows

dependencies:
  camera_platform_interface:
    git: https://github.com/kumsumit/camera_platform_interface.git
  cross_file: ^0.3.4+2
  flutter:
    sdk: flutter
  stream_transform: ^2.1.1

dev_dependencies:
  async: ^2.5.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  leak_tracker_flutter_testing: any
  mockito: ^5.4.4
  pigeon: ^22.6.0

topics:
  - camera
